### PR TITLE
Definitions for pdfe library.

### PR DESCRIPTION
**Pull request by AndreasMatthias**

### CODE REVIEW

**Comment by Josef-Friedrich** [comment]
Thank you very much for your contribution

**Comment by Josef-Friedrich** [comment]
https://github.com/Josef-Friedrich/LuaTeX_Lua-API/commit/af20f1174099480e98282308ec63e68ddc350b31

**Comment by Josef-Friedrich** [comment]
The development of the definitions for LuaTeX takes place in this repository: https://github.com/Josef-Friedrich/LuaTeX_Lua-API.

**Comment by AndreasMatthias** [comment]
Sorry, I haven't noticed this. Ok, I'll fork your upstream repository.

**Pull request merged**
